name = "nakai_build"
version = "1.0.0"
licences = ["MIT"]
description = "Our website (written using Nakai) âœ¨"
repository = { type = "github", user = "nakaibuild", repo = "nakai.build" }

target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.22"
nakai = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 0.6"
